# Generated by Django 4.1.9 on 2024-04-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0004_alter_registration_registration_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_User',
        ),
    ]
