# Generated by Django 4.1.9 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0007_student_registration_number_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
