# Generated by Django 4.1.9 on 2024-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0010_alter_registration_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default=None, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
