# Generated by Django 4.1.9 on 2024-04-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0012_alter_student_do_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.CharField(max_length=12, unique=True)),
                ('college_name', models.CharField(max_length=100)),
                ('college_type', models.PositiveIntegerField(choices=[(1, 'Central'), (2, 'Affiliated')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8, unique=True)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_id', models.CharField(max_length=12, unique=True)),
                ('depart_name', models.CharField(max_length=35)),
                ('courses', models.ManyToManyField(related_name='departments', to='siddh_app.course')),
            ],
        ),
    ]
