# Generated by Django 4.1.9 on 2024-04-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0014_student_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='depart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siddh_app.department'),
        ),
    ]
