# Generated by Django 4.1.9 on 2024-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0017_program_remove_student_depart_delete_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
