# Generated by Django 4.1.9 on 2024-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0018_alter_program_program_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AlterField(
            model_name='program',
            name='courses',
            field=models.ManyToManyField(related_name='programs', to='siddh_app.course'),
        ),
    ]
