# Generated by Django 4.1.9 on 2024-04-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0021_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siddh_app.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siddh_app.program')),
            ],
            options={
                'unique_together': {('program', 'course')},
            },
        ),
    ]
