# Generated by Django 4.1.9 on 2024-04-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0027_alter_programcourse_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcourse',
            name='semester',
        ),
    ]
