# Generated by Django 4.1.9 on 2024-04-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0028_remove_programcourse_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siddh_app.course')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siddh_app.student')),
            ],
        ),
    ]
