# Generated by Django 4.1.9 on 2024-04-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0029_alter_program_program_name_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siddh_app.program'),
        ),
    ]
