# Generated by Django 4.1.9 on 2024-04-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0030_remove_course_faculty_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
