# Generated by Django 4.1.9 on 2024-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0032_programcourse_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='credit_hour',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
