# Generated by Django 4.1.9 on 2024-04-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0038_alter_programcourse_credit_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcourse',
            name='credit_hour',
        ),
    ]
