# Generated by Django 4.1.9 on 2024-04-28 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0041_alter_programcourse_credit_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(10)])),
                ('semester_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(through='siddh_app.ProgramCourse', to='siddh_app.program'),
        ),
        migrations.AddField(
            model_name='student',
            name='program_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siddh_app.programcourse'),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.AddField(
            model_name='mark',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siddh_app.course'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siddh_app.student'),
        ),
        migrations.AlterField(
            model_name='programcourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siddh_app.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siddh_app.semester'),
        ),
    ]
