# Generated by Django 4.1.9 on 2024-04-28 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddh_app', '0043_remove_student_program_course_student_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_id',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
